version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "beta"
    labels:
      - "npm"
      - "dependencies"

  - package-ecosystem: "yarn"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "yarn"
      - "dependencies"